### PR TITLE
Fixes issue #14 (child exception not throw)

### PR DESCRIPTION
**Pull request by marianoarga**

### CODE REVIEW

**Comment by marianoarga** [comment]
Added minor fix to undefined variable.

**Comment by SleepWalker** [comment]
Hi, @marianoarga. Many thanks for the first two commits!
With the last one probably it will be better to make icon version optional by adding new property e.g. `onlyIcons` to HOAuth.php and HOAuthActive.php (and don't forget to put this property in `render()` method) and also write something like the following in link.php:

``` php
<?php
/**
 * @var HOAuthWidget $this
 * @var string $provider name of provider
 * @var boolean $onlyIcons flag that displays buttons as icons without any text
 */

$additionalClass = $onlyIcons ? 'icon' : '';
$invitation = Yii::app()->user->isGuest ? HOAuthAction::t('Sign in with') : HOAuthAction::t('Connect with');
?>
<p>
    <a href="<?php echo Yii::app()->createUrl($this->route . '/oauth', array('provider' => $provider)); ?>" class="zocial <?php  echo $additionalClass . ' ' . strtolower($provider) ?>"><?php  echo "$invitation $provider"; ?></a>
</p>
```

Can you apply this changes or I can merge only with two first commits. And you can also write about this changes in CHANGELOG file. Thanks!

P.S. Sorry for my slow response.

**Comment by marianoarga** [comment]
Hello @SleepWalker. I'm currently fully working on a project and the last commit was accidentaly commited to this fork (I have made 'default' zocial icon in the other project), you can merge the other commits, since I don't know when i'll be available for contributing again, sorry.

Thanks for this great extension.

**Comment by SleepWalker** [comment]
Ok, so I will merge the first two commits and implement the icon support later by myself. I am busy at the moment too :)

Thanks for contributing!

**Comment by SleepWalker** [comment]
BTW, @marianoarga, I have just pushed new code from local repo, where is implemented the support of 'only icons' and also authentication in popup window. Probably we should write js code for that not in file (as it is now), but right in page and with popup window size (or better to make this option changeable by the user?).

**Comment by marianoarga** [comment]
I don't really understand what you mean, I see in the code you have already added the 'onlyIcons' option, are you proposing to allow the user to config the window pop-up size?

**Comment by SleepWalker** [comment]
Yes, you are right and probably an ooptional url, where the user will be redirected after login...

**Comment by marianoarga** [comment]
I'm out of time to contribute with this :(

**Comment by SleepWalker** [comment]
Ok, no Problem!

**Pull request closed without merging**
